apiVersion: v1
kind: PersistentVolume
metadata:
  name: aipf-pv
  namespace: aipf
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/ubuntu/alliedipfirm.com
    type: DirectoryOrCreate