apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aipf-pvc
  namespace: aipf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard